name: Run Client Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm install

    - name: Run client unit tests
      run: npm run test -w client

    - name: Run server unit tests with coverage
      run: npm run test:coverage -w server

    - name: Install Playwright dependencies
      run: npx playwright install

    - name: Run E2E tests
      run: npm run test:e2e -w client
